version: 2.1

orbs:
  codecov: codecov/codecov@3.1.0

jobs:

  analyze-and-test:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: |
          dart run build_runner build
          flutter doctor
          flutter analyze
          flutter test 

workflows:
  version: 2.1
  ci:
    jobs:
      - analyze-and-test
  upload-to-codecov:
    jobs:
      - checkout
      - codecov/upload
