version: 2.1

# orbs:
#   codecov: codecov/codecov@1.2.5

jobs:

  test:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: |
          flutter doctor
          flutter test 

workflows:
  version: 2.1
  ci:
    jobs:
      - test
