version: 2.1

# orbs:
#   codecov: codecov/codecov@1.2.5

jobs:
  init:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor

  test:
    steps:
      - run: flutter test 

workflows:
  version: 2.1
  ci:
    jobs:
      - init
      - test
